### ISSUE TITLE
FAQ: what do you do about YT-side compression? 

### ISSUE THREAD

**Issue by excenter** [xhighway999/PygaMasher#1]
Exemplified [here](https://youtu.be/icruGcSsPp0) Youtube applies compression to the video. 
Does this introduce data loss?

**Comment by xhighway999** [comment]
Yes, in such cases you would lose data. The best way to counteract this would be to implement an error-correcting code, something like [Reed-Solomon error correction](https://en.wikipedia.org/wiki/Reed%E2%80%93Solomon_error_correction).

**Comment by xhighway999** [comment]
PygaMasher now includes Reed-Solomon error correction and should handle minor compression artifacts.
